import type { NextPage } from 'next';
import Head from 'next/head';
import NavigationBar from "../components/NavigationBar";
import { useEffect, useState } from "react";
import { NFTItem } from "../schemas/NFTItem";
import { ALLNFTs } from "../schemas/TestData";
import NFTListing from "../components/NFTListing";

const Home: NextPage = () => {
    const [NFTItems, setNFTItems] = useState<NFTItem[]>([]);

    useEffect(() => {
        loadAvailableNFTs();
    });

    async function loadAvailableNFTs() {
        setNFTItems(ALLNFTs);
    }

    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <NavigationBar />
            <main className={"m-10"}>
                <NFTListing nftItems={NFTItems} sell={true} />
            </main>
    </div>
  )
};

export default Home;
